// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_user_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_user_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "202212181137508_mig_user_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
